- name: configure react instance
  hosts: _ansible_react
  become: true
  tasks:
    - name: upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
    # we may need to uninstall any existing docker files from the centos repo first.
    - name: Remove old docker packages
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed
    - name: Install yum utils
      ansible.builtin.yum:
        name: "yum-utils"
        state: latest
    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
    # at this point do not forget change DB_HOST env variable for postgresql node
    - name: copy files to the react node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/react/
        dest: /home/ec2-user/react
    - name: remove cw_react container
      community.docker.docker_container:
        name: cw_react
        state: absent
        force_kill: true
    - name: remove clarusway/react image
      community.docker.docker_image:
        name: clarusway/react
        state: absent

    - name: build docker image
      community.docker.docker_image:
        name: clarusway/react
        build:
          path: /home/ec2-user/react
        source: build
        state: present
      register: image_info

    - name: Print the image_info
      ansible.builtin.debug:
        var: image_info

    - name: run react docker container
      community.docker.docker_container:
        name: cw_react
        image: clarusway/react
        state: started
        ports:
        - "3000:3000"
      register: container_info

    - name: Print the container info
      ansible.builtin.debug:
        var: container_info